
spring:
  shardingsphere:
    datasource:
      names: master,slave
#      common:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/test
        username:
        password:
      slave:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/test
        username:
        password:
    rules:
      readwrite-splitting:
        data-sources:
          readwrite:
            write-data-source-name: master
            read-data-source-names: slave
            load-balancer-name: round_robin